# frozen_string_literal: true

tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "microsoft/git"
tap "mike-engel/jwt-cli"
tap "thought-machine/please"

brew "circleci"
brew "ctags"
brew "direnv"
brew "gh"
brew "git"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "jq"
brew "neovim"
brew "node-build"
brew "nodenv"
brew "pnpm"
brew "pyenv"
brew "siege"
brew "tree"
brew "vim"
brew "websocat"
brew "yq"
brew "zeromq"
brew "mike-engel/jwt-cli/jwt-cli"
brew "thought-machine/please/please"

cask "font-ricty-diminished"
cask "git-credential-manager-core"
cask "ngrok"
