#!/bin/zsh

# backup
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
mv -v ~/.vim ~/.vim.old 2> /dev/null

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
curl --insecure -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# vimr
ln -sf $BASE/.vimrc ~/.vimrc
ln -sf $BASE/.vim/keymap.vim ~/.vim/

# nvim
# mkdir -p ~/.config/nvim/autoload
# ln -sf $BASE/vimrc ~/.config/nvim/init.vim
# ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/
# 
# mkdir -p ~/.config/nvim
# ln -sf $BASE/coc-settings.json ~/.config/nvim/coc-settings.json
# 
# vim +PlugInstall +qall
