#!/bin/bash
cd $(dirname $BASH_SOURCE)
BASE=$(pwd)


# Zsh
rm -rf $HOME/.zshrc
ln -sf $BASE/.zshrc $HOME/.zshrc
ln -sf $BASE/.zshrc.custom $HOME/.zshrc.custom
ln -sf $BASE/.zshrc.brewbundle $HOME/.zshrc.brewbundle
touch  $HOME/.zshrc.env


# Homebrew
source $HOME/.zshrc.brewbundle
brew update
brew bundle --no-lock --file ./Brewfile


# Vim
### backup
rm -rf ~/.vimrc.old ~/.vim.old
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
mv -v ~/.vim ~/.vim.old 2> /dev/null
### install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
### symlinks
ln -sf $BASE/.vimrc ~/.vimrc
ln -sf $BASE/.vim/config ~/.vim/config
### install plugins
vim +PlugInstall +qa
