#!/bin/bash
cd $(dirname $BASH_SOURCE)
BASE=$(pwd)
 
# Zsh
rm -rf $HOME/.zshrc
ln -sf $BASE/.zshrc $HOME/.zshrc
ln -sf $BASE/.zshrc.custom $HOME/.zshrc.custom
ln -sf $BASE/.zshrc.brewbundle $HOME/.zshrc.brewbundle
touch $HOME/.zshrc.env

# Homebrew
source $HOME/.zshrc.brewbundle
brew update
brew bundle --no-lock --file ./Brewfile

# Version Manager
ln -sf $BASE/.tool-versions ~/.tool-versions
xargs -I x asdf plugin add x < asdf-plugins.txt


# Vim
rm -rf ~/.vimrc ~/.vim
### install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
### symlinks
ln -sf $BASE/.vimrc ~/.vimrc
ln -sf $BASE/.vim/config ~/.vim/
### install plugins
vim +PlugInstall +qa
